# pythonのTags名を指定
FROM python:3.9.6-slim

# 処理を実行するフォルダ名を指定
WORKDIR /src

# copy src
COPY ./ /

# install system dependencies
RUN apt-get update && \
    apt-get install -y \
        build-essential \
        python3-dev \
        python3-setuptools \
        libpq-dev\
        make \
        gcc

# 使用するライブラリのインストール
RUN pip install --upgrade pip
COPY ./src/requirements.txt /src/requirements.txt
RUN python3 -m pip install -r /src/requirements.txt

# マイグレーションに関するファイルのコピー
COPY ./src/migrations /src/migrations
COPY ./src/alembic.ini /src/alembic.ini

# ------
RUN apt-get remove -y --purge make gcc build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# FastAPI起動コマンド
# CMD ["uvicorn", "main:app","--reload", "--host", "0.0.0.0", "--port", "8000"]
CMD ["gunicorn", "main:app", "--workers", "4", "--reload", "--bind", "0.0.0.0:8000"]

EXPOSE 8000
